version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    time: "12:00"
    timezone: Asia/Singapore
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: y18n
    versions:
    - 4.0.1
  - dependency-name: faunadb
    versions:
    - 4.0.0
    - 4.0.2
    - 4.0.3
    - 4.1.0
    - 4.1.1
    - 4.1.3
  - dependency-name: telegraf
    versions:
    - 4.0.1
    - 4.0.2
    - 4.0.3
    - 4.1.0
    - 4.1.1
    - 4.1.2
    - 4.2.1
  - dependency-name: netlify-lambda
    versions:
    - 2.0.3
  - dependency-name: cheerio
    versions:
    - 1.0.0-rc.5
